version: '3.8'

services:
  unagi-dev:
    build: .
    volumes:
      - .:/workspace
    environment:
      - GITHUB_TOKEN=${UNAGI_DEV_PAT}  # Read-only PAT
      - GOOSE_DEFAULT_PROVIDER=grok
    ports:
      - "8000:8000"  # For Unagi app
    depends_on:
      - mcp-server

  mcp-server:
    build:
      context: https://github.com/modelcontextprotocol/servers.git#2025.4.24
      dockerfile: src/github/Dockerfile
    platform: linux/arm64  # For Apple Silicon
    environment:
      - GITHUB_TOKEN=${MCP_PAT}  # Same read-only PAT
      - TOOLSETS=context,issues,pull_requests,repos,notifications  # Limit to reads
      - PORT=8080
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  workspace: {}