version: '3.8'

services:
  unagi-dev:
    build:
      context: .
      dockerfile: Dockerfile  # Your existing Goose/Gemini CLI Dockerfile (python:3.11-slim base)
    volumes:
      - .:/workspace
    environment:
      - GOOSE_DEFAULT_PROVIDER=grok
      - GITHUB_PAT=${GITHUB_PAT}  # Read-only PAT from your env
    platform: linux/arm64  # Ensure native Apple Silicon performance

  mcp-server:
    build:
      context: https://github.com/docker/mcp-servers.git
      dockerfile: src/github/Dockerfile  # Assumes there's a Dockerfile in that path (based on repo structure)
    environment:
      - GITHUB_TOKEN=${GITHUB_PAT}  # Inject read-only PAT
      - TOOLSETS=context,issues,pull_requests,repos,notifications  # Limit to read-only toolsets
    ports:
      - "8080:8080"  # Expose the MCP API (adjust port if needed)
    depends_on:
      - unagi-dev  # Ensure it starts after the main dev container
    platform: linux/arm64